In [2]:
import pandas as pd

In [3]:
data = {
    "Role" : [
        "Data Analyst",
        "Data Scientist",
        "Data Engineer",
        "Machine Learning Engineer",
        "AI Engineer",
        "Frontend Developer",
        "Backend Developer",
        "Full Stack Developer",
        "Software Engineer",
        "Mobile App Developer",
        "Blockchain Developer",
        "DevOps Engineer",
        "Cloud Engineer",
        "Network Engineer",
        "Cybersecurity Analyst",
        "UI/UX Designer",
        "Graphic Designer",
        "Businees Analyst",
        "QA Engineer",
        "Technical Support Engineer"
        ],

    "Skills" : [
        "Python|SQL|Excel|Power BI",
        "Python|Machine Learning|Statistics|Deep Learning",
        "Python|SQL|ETL|Big Data",
        "Python|Machine Learning|Deep Learning|Tensor Flow",
        "Python| Deep Learning|NLP|AI",
        "HTML|CSS|Javascript|React",
        "Python|Django|SQL|APIs",
        "HTML|CSS|Javascript|Python",
        "Java|DSA|OOP|System Designer",
        "Java|Kotlin|Android|APIs",
        "Blockchain|Solidity|Cryptography",
        "Docker|Kubernetes|CI/CD|Linux",
        "AWS|Azure|Cloud|Networking",
        "Networking|Routing|Linux",
        "Security|Networking|Ethical Hacking",
        "Figma|Wireframing|User Research",
        "Photoshop|Illustrator|Creativity",
        "Excel|SQL|Communication|Analysis",
        "Testing|Automation|Selenium",
        "Troubleshooting|Networking|Customer Support"
    ]
}

In [4]:
len(data["Role"])

20

In [5]:
len(data["Skills"])

20

In [6]:
df = pd.DataFrame(data)

In [7]:
df

,Role,Skills
0,Data Analyst,Python|SQL|Excel|Power BI
1,Data Scientist,Python|Machine Learning|Statistics|Deep Learning
2,Data Engineer,Python|SQL|ETL|Big Data
3,Machine Learning Engineer,Python|Machine Learning|Deep Learning|Tensor Flow
4,AI Engineer,Python| Deep Learning|NLP|AI
5,Frontend Developer,HTML|CSS|Javascript|React
6,Backend Developer,Python|Django|SQL|APIs
7,Full Stack Developer,HTML|CSS|Javascript|Python
8,Software Engineer,Java|DSA|OOP|System Designer
9,Mobile App Developer,Java|Kotlin|Android|APIs
10,Blockchain Developer,Blockchain|Solidity|Cryptography
11,DevOps Engineer,Docker|Kubernetes|CI/CD|Linux
12,Cloud Engineer,AWS|Azure|Cloud|Networking
13,Network Engineer,Networking|Routing|Linux
14,Cybersecurity Analyst,Security|Networking|Ethical Hacking
15,UI/UX Designer,Figma|Wireframing|User Research
16,Graphic Designer,Photoshop|Illustrator|Creativity
17,Businees Analyst,Excel|SQL|Communication|Analysis
18,QA Engineer,Testing|Automation|Selenium
19,Technical Support Engineer,Troubleshooting|Networking|Customer Support

In [8]:
df["Skills"] = df["Skills"].apply(lambda x: x.split("|"))

In [9]:
df["Skills"] = df["Skills"].apply(lambda x:[skill.lower() for skill in x])

In [10]:
df.head()

,Role,Skills
0,Data Analyst,"[python, sql, excel, power bi]"
1,Data Scientist,"[python, machine learning, statistics, deep le..."
2,Data Engineer,"[python, sql, etl, big data]"
3,Machine Learning Engineer,"[python, machine learning, deep learning, tens..."
4,AI Engineer,"[python, deep learning, nlp, ai]"

In [11]:
user_input = input("Enter your skills : ")
user_skills = [skill.strip().lower() for skill in user_input.split(",")]
print(user_skills)

Enter your skills :  python,java,sql

['python', 'java', 'sql']

In [12]:
results = []
for index, row in df.iterrows():
    role = row["Role"]
    required_skills = row["Skills"]

    matched = [skill for skill in user_skills if skill in required_skills]

    score = (len(matched)/len(required_skills))*100

    missing = [skill for skill in required_skills if skill not in user_skills]

    results.append({
        "Role" : role,
        "Match %" : round(score,2),
        "Missing Skills" : missing
    })

In [13]:
for r in results:
    print(r)

{'Role': 'Data Analyst', 'Match %': 50.0, 'Missing Skills': ['excel', 'power bi']}
{'Role': 'Data Scientist', 'Match %': 25.0, 'Missing Skills': ['machine learning', 'statistics', 'deep learning']}
{'Role': 'Data Engineer', 'Match %': 50.0, 'Missing Skills': ['etl', 'big data']}
{'Role': 'Machine Learning Engineer', 'Match %': 25.0, 'Missing Skills': ['machine learning', 'deep learning', 'tensor flow']}
{'Role': 'AI Engineer', 'Match %': 25.0, 'Missing Skills': [' deep learning', 'nlp', 'ai']}
{'Role': 'Frontend Developer', 'Match %': 0.0, 'Missing Skills': ['html', 'css', 'javascript', 'react']}
{'Role': 'Backend Developer', 'Match %': 50.0, 'Missing Skills': ['django', 'apis']}
{'Role': 'Full Stack Developer', 'Match %': 25.0, 'Missing Skills': ['html', 'css', 'javascript']}
{'Role': 'Software Engineer', 'Match %': 25.0, 'Missing Skills': ['dsa', 'oop', 'system designer']}
{'Role': 'Mobile App Developer', 'Match %': 25.0, 'Missing Skills': ['kotlin', 'android', 'apis']}
{'Role': 'Blockchain Developer', 'Match %': 0.0, 'Missing Skills': ['blockchain', 'solidity', 'cryptography']}
{'Role': 'DevOps Engineer', 'Match %': 0.0, 'Missing Skills': ['docker', 'kubernetes', 'ci/cd', 'linux']}
{'Role': 'Cloud Engineer', 'Match %': 0.0, 'Missing Skills': ['aws', 'azure', 'cloud', 'networking']}
{'Role': 'Network Engineer', 'Match %': 0.0, 'Missing Skills': ['networking', 'routing', 'linux']}
{'Role': 'Cybersecurity Analyst', 'Match %': 0.0, 'Missing Skills': ['security', 'networking', 'ethical hacking']}
{'Role': 'UI/UX Designer', 'Match %': 0.0, 'Missing Skills': ['figma', 'wireframing', 'user research']}
{'Role': 'Graphic Designer', 'Match %': 0.0, 'Missing Skills': ['photoshop', 'illustrator', 'creativity']}
{'Role': 'Businees Analyst', 'Match %': 25.0, 'Missing Skills': ['excel', 'communication', 'analysis']}
{'Role': 'QA Engineer', 'Match %': 0.0, 'Missing Skills': ['testing', 'automation', 'selenium']}
{'Role': 'Technical Support Engineer', 'Match %': 0.0, 'Missing Skills': ['troubleshooting', 'networking', 'customer support']}

In [14]:
results_df = pd.DataFrame(results)
results_df

,Role,Match %,Missing Skills
0,Data Analyst,50.0,"[excel, power bi]"
1,Data Scientist,25.0,"[machine learning, statistics, deep learning]"
2,Data Engineer,50.0,"[etl, big data]"
3,Machine Learning Engineer,25.0,"[machine learning, deep learning, tensor flow]"
4,AI Engineer,25.0,"[ deep learning, nlp, ai]"
5,Frontend Developer,0.0,"[html, css, javascript, react]"
6,Backend Developer,50.0,"[django, apis]"
7,Full Stack Developer,25.0,"[html, css, javascript]"
8,Software Engineer,25.0,"[dsa, oop, system designer]"
9,Mobile App Developer,25.0,"[kotlin, android, apis]"
10,Blockchain Developer,0.0,"[blockchain, solidity, cryptography]"
11,DevOps Engineer,0.0,"[docker, kubernetes, ci/cd, linux]"
12,Cloud Engineer,0.0,"[aws, azure, cloud, networking]"
13,Network Engineer,0.0,"[networking, routing, linux]"
14,Cybersecurity Analyst,0.0,"[security, networking, ethical hacking]"
15,UI/UX Designer,0.0,"[figma, wireframing, user research]"
16,Graphic Designer,0.0,"[photoshop, illustrator, creativity]"
17,Businees Analyst,25.0,"[excel, communication, analysis]"
18,QA Engineer,0.0,"[testing, automation, selenium]"
19,Technical Support Engineer,0.0,"[troubleshooting, networking, customer support]"

In [15]:
results_df = results_df.sort_values(by = "Match %", ascending = False)

In [16]:
top_jobs = results_df.head(5)
top_jobs

,Role,Match %,Missing Skills
0,Data Analyst,50.0,"[excel, power bi]"
2,Data Engineer,50.0,"[etl, big data]"
6,Backend Developer,50.0,"[django, apis]"
1,Data Scientist,25.0,"[machine learning, statistics, deep learning]"
3,Machine Learning Engineer,25.0,"[machine learning, deep learning, tensor flow]"

In [32]:
for index , row in top_jobs.iterrows():
    print("Role : ",row["Role"])
    print("Match % : ",row["Match %"])
    print("Missing Skills :", ",". join (row["Missing Skills"]))
    print("-" * 40)

Role :  Data Analyst
Match % :  50.0
Missing Skills : excel,power bi
----------------------------------------
Role :  Data Engineer
Match % :  50.0
Missing Skills : etl,big data
----------------------------------------
Role :  Backend Developer
Match % :  50.0
Missing Skills : django,apis
----------------------------------------

In [33]:
results_df = results_df[results_df["Match %"]>=30]

In [34]:
top_jobs = results_df.head(5)

In [35]:
top_jobs

                Role  Match %     Missing Skills
0       Data Analyst     50.0  [excel, power bi]
2      Data Engineer     50.0    [etl, big data]
6  Backend Developer     50.0     [django, apis]

In [36]:
if len(top_jobs) == 0:
    print("No matching jobs found . Try adding more skills.")
else:
    print("Top Job Recommendation :\n")
    for index,row in top_jobs.iterrows():
        print("Role :", row["Role"])
        print("Match % :" , round(row["Match %"],1))
        print("Missing Skills :",",".join([skill.upper() for skill in row["Missing Skills"]]))
        print("-" * 40)

Top Job Recommendation :

Role : Data Analyst
Match % : 50.0
Missing Skills : EXCEL,POWER BI
----------------------------------------
Role : Data Engineer
Match % : 50.0
Missing Skills : ETL,BIG DATA
----------------------------------------
Role : Backend Developer
Match % : 50.0
Missing Skills : DJANGO,APIS
----------------------------------------

In [37]:
best_job = top_jobs.iloc[0]
print("\nBest Match for You:")
print("Role:",best_job["Role"])
print("Match %",best_job["Match %"])

Best Match for You:
Role: Data Analyst
Match % 50.0

In [27]:
df.to_csv("jobs_data.csv",index = False)